# Generated by Django 5.1.6 on 2025-03-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0008_remove_transaction_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
