# Generated by Django 5.1.4 on 2025-03-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0009_remove_fooditem_stock_quantity_fooditem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='stock_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
