# Generated by Django 5.1.4 on 2025-03-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0010_fooditem_stock_quantity_alter_fooditem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='stock_quantity',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
