# Generated by Django 5.1.4 on 2025-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0011_alter_fooditem_name_alter_fooditem_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='stock_quantity',
            field=models.IntegerField(),
        ),
    ]
