# Generated by Django 5.1.4 on 2025-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0014_remove_cart_cart_id_remove_cart_special_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_items/'),
        ),
    ]
