# Generated by Django 5.1.4 on 2025-03-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_items', '0017_customizationgroup_customizationoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
